name: dcm2bids
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - dcm2bids=3.2.0
  - dcm2niix=1.0.20250506
  - dcmtk=3.6.1
  - icu=73.1
  - jpeg=9f
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libmpdec=4.0.0
  - libpng=1.6.50
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=25.3
  - python=3.9.18
  - readline=8.2
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - asttokens==3.0.1
      - boto3==1.42.29
      - botocore==1.42.29
      - comm==0.2.3
      - debugpy==1.8.18
      - decorator==5.2.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipykernel==6.31.0
      - ipython==8.18.1
      - jedi==0.19.2
      - jmespath==1.0.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - matplotlib-inline==0.2.1
      - nest-asyncio==1.6.0
      - nibabel==5.3.3
      - numpy==2.0.2
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.4.0
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydicom==2.4.4
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pyzmq==27.1.0
      - s3transfer==0.16.0
      - six==1.17.0
      - stack-data==0.6.3
      - tornado==6.5.3
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - urllib3==1.26.20
      - wcwidth==0.2.14
      - zipp==3.23.0
